name: Build Windows Wallet

on:
  workflow_dispatch:
  push:
    branches: [ master, main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          choco install bdb boost openssl

      - name: Build Kapcoin
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" -A x64 ..
          cmake --build . --config Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: kapcoin-windows-wallet
          path: build/src/qt/Release/kapcoin-qt.exe
