name: Build Windows Wallet
on: [workflow_dispatch, push]

jobs:
  build-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git
          sudo apt-get install -y g++-mingw-w64-x86-64

      - name: Build Wallet
        run: |
          # Questo comando prepara il compilatore per Windows dentro Linux
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
          
          # Entriamo nella cartella delle dipendenze e le costruiamo
          cd depends
          make HOST=x86_64-w64-mingw32 -j$(nproc)
          cd ..
          
          # Compiliamo il wallet vero e proprio
          ./autogen.sh
          ./configure --prefix=`pwd`/depends/x86_64-w64-mingw32
          make -j$(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kapcoin-windows-exe
          path: |
            src/qt/kapcoin-qt.exe
            src/kapcoind.exe
