name: Build Windows Daemon
on: [workflow_dispatch, push]

jobs:
  build-windows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git g++-mingw-w64-x86_64

      - name: Build Kapcoin Daemon
        run: |
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
          
          # Costruiamo le dipendenze ESCLUDENDO la grafica (Qt)
          cd depends
          make HOST=x86_64-w64-mingw32 NO_QT=1 -j$(nproc)
          cd ..
          
          # Compiliamo solo il daemon e il CLI
          ./autogen.sh
          ./configure --prefix=`pwd`/depends/x86_64-w64-mingw32 --without-gui --without-miniupnpc --disable-tests --disable-bench
          make -j$(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kapcoin-daemon-windows
          path: |
            src/kapcoind.exe
            src/kapcoin-cli.exe
